name: Teste Clair

on:
  workflow_dispatch:

jobs:
  createClairCache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
        
      - name: Set permission
        run: |
          mkdir ${GITHUB_WORKSPACE}/clairdb
          sudo chmod -R 777 clairdb

      - name: set cache DB
        uses: actions/cache@v3
        with:
          path: clairdb
          key: clair-db

      - name: setup database
        shell: bash
        run: docker run -v ${GITHUB_WORKSPACE}/clairdb:/var/lib/postgresql/clair -p 5432:5432 -d --name db arminc/clair-db:$(date +%Y-%m-%d)

      - name: overwrite permission
        run: |
          sudo chmod -R 777 clairdb

      - name: Listar diretório
        run: |
          cd clairdb
          ls

      - name: Wait for database
        run: |
          sleep 15

      - name: Run Clair
        shell: bash  
        run: |  
          docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:latest

      - name: Give permission
        run: chmod +x .github/workflows/clair-check.sh

      - name: Checking
        shell: bash
        run: |
          .github/workflows/clair-check.sh

      - name: Docker logs
        run: |
          docker logs clair

      - name: Listar diretório
        run: |
          sudo chmod -R 777 clairdb
          cd clairdb
          ls